defaults:
  - process: process1
  - model: model2
  - _self_ 

raw:
  dir: data/raw
  schema_teams: 
    - h_a
    - xG
    - xGA
    - npxG
    - npxGA
    - deep
    - deep_allowed
    - scored
    - missed
    - xpts
    - result
    - date
    - wins
    - draws
    - loses
    - pts
    - npxGD
    - ppda.att
    - ppda.def
    - ppda_allowed.att
    - ppda_allowed.def

processed:
  dir: data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

to_predict:
  dir: data/to_predict
  name: to_predict.csv
  path: ${to_predict.dir}/${to_predict.name}